# Build stage
FROM node:18-alpine as builder
WORKDIR /app

COPY package*.json prisma ./
RUN npm install

COPY . .
RUN npx prisma generate
RUN npm run build

# Production stage
FROM node:18-alpine
WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/package*.json ./

# Si el .env lo manejas por docker-compose, no copies aquí
COPY .env .env

EXPOSE 3000
CMD ["node", "dist/main"]
