
services:
  backend:
    build: 
      context: ../backend-collab-slides
    env_file:
      - ./env/backend.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - minio
    networks:
      - slides-network
    restart: unless-stopped

  frontend:
    build: 
      context: ../frontend-collab-slides
    ports:
      - "80:80"
    networks:
      - slides-network
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: slideuser
      POSTGRES_PASSWORD: slidepass
      POSTGRES_DB: slidesdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - slides-network
    restart: unless-stopped

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    networks:
      - slides-network
    restart: unless-stopped

volumes:
  postgres-data:
  minio-data:

networks:
  slides-network: